version: '3.4'

x-cache-from:
  - &api-cache-from
    cache_from:
      - ${NGINX_IMAGE:-quay.io/api-platform/nginx}
      - ${PHP_IMAGE:-quay.io/api-platform/php}

services:
  php:
    build:
      context: ./api
      args:
      - HTTP_PROXY_URL=${HTTP_PROXY_URL}
      - HTTPS_PROXY_URL=${HTTPS_PROXY_URL}
      target: api_platform_php
      <<: *api-cache-from
    image: ${PHP_IMAGE:-quay.io/api-platform/php}
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - db
      - dev-tls
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
      - dev-certs:/certs:ro,nocopy

  api:
    build:
      context: ./api
      args:
      - HTTP_PROXY_URL=${HTTP_PROXY_URL}
      - HTTPS_PROXY_URL=${HTTPS_PROXY_URL}
      target: api_platform_nginx
      <<: *api-cache-from
    image: ${NGINX_IMAGE:-quay.io/api-platform/nginx}
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:ro
    ports:
      - target: 80
        published: 8000
        protocol: tcp

  vulcain:
    image: dunglas/vulcain
    environment:
      - CERT_FILE=/certs/localhost.crt
      - KEY_FILE=/certs/localhost.key
      - UPSTREAM=http://api
    depends_on:
      - api
      - dev-tls
    volumes:
      - dev-certs:/certs:ro,nocopy
    ports:
      - target: 443
        published: 8443
        protocol: tcp

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_USER=api-platform
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./api/docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  mercure:
    image: dunglas/mercure
    environment:
      - ALLOW_ANONYMOUS=1
      - CERT_FILE=/certs/localhost.crt
      - CORS_ALLOWED_ORIGINS=*
      - DEMO=1
      - JWT_KEY=!ChangeMe!
      - KEY_FILE=/certs/localhost.key
      - PUBLISH_ALLOWED_ORIGINS=https://localhost:1337 # required for publishing from the demo page
    depends_on:
      - dev-tls
    volumes:
      - dev-certs:/certs:ro,nocopy
    ports:
      - target: 443
        published: 1337
        protocol: tcp

  dev-tls:
    build:
      context: ./docker/dev-tls
    volumes:
      - dev-certs:/certs:rw
    ports:
      - target: 80
        published: 80
        protocol: tcp

  db_codimd:
    image: postgres:latest
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=change_password
      - POSTGRES_DB=codimd
    volumes:
      - "db-codimd-data:/var/lib/postgresql/data"
    restart: always

  codimd:
    image: nabo.codimd.dev/hackmdio/hackmd:latest
    environment:
      - CMD_DB_URL=postgres://codimd:change_password@db_codimd/codimd
      - CMD_USECDN=false
    depends_on:
      - db_codimd
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    restart: always

  client:
    build:
      context: ./client
      args:
      - HTTP_PROXY_URL=${HTTP_PROXY_URL}
      - HTTPS_PROXY_URL=${HTTPS_PROXY_URL}
      target: client_angular
    image: node:latest
    environment:
      - PATH=/app/node_modules/.bin:$PATH
    ports:
      - target: 4200
        published: 4200
        protocol: tcp
    volumes:
      - client:/app
    depends_on:
      - api
      - dev-tls
  bitwarden:
    image: bitwardenrs/server:latest #swap tag to raspberry to run on a raspberry pi
    ports:
      - target: 80
        published: 8888
        protocol: tcp
    volumes:
      - ./data/bitwarden:/data
    restart: on-failure

volumes:
  db-data: {}
  db-codimd-data: {}
  dev-certs: {}
  upload-data: {}
  client: {}
