# api/config/packages/security.yaml
security:
  encoders:
    App\Entity\User:
      algorithm: argon2i

  role_hierarchy:
    # CLIENT RELATED ROLES
    ROLE_CLIENT_GET_LIST:
    ROLE_CLIENT_POST:
    ROLE_CLIENT_PUT:
    ROLE_CLIENT_PATCH:
    ROLE_CLIENT_DELETE:
    ROLE_CLIENT_GET_ITEM:

    # HOST RELATED ROLES
    ROLE_HOST_GET_LIST:
    ROLE_HOST_POST:
    ROLE_HOST_PUT:
    ROLE_HOST_PATCH:
    ROLE_HOST_DELETE:
    ROLE_HOST_GET_ITEM:

    # HOST_VULN RELATED ROLES
    ROLE_HOST_VULN_GET_LIST:
    ROLE_HOST_VULN_POST:
    ROLE_HOST_VULN_PUT:
    ROLE_HOST_VULN_PATCH:
    ROLE_HOST_VULN_DELETE:
    ROLE_HOST_VULN_GET_ITEM:

    # IMPACT RELATED ROLES
    ROLE_IMPACT_GET_LIST:
    ROLE_IMPACT_POST:
    ROLE_IMPACT_PUT:
    ROLE_IMPACT_PATCH:
    ROLE_IMPACT_DELETE:
    ROLE_IMPACT_GET_ITEM:

    # MISSION RELATED ROLES
    ROLE_MISSION_GET_LIST:
    ROLE_MISSION_POST:
    ROLE_MISSION_PUT:
    ROLE_MISSION_PATCH:
    ROLE_MISSION_DELETE:
    ROLE_MISSION_GET_ITEM:

    # MISSION_TYPE RELATED ROLES
    ROLE_MISSION_TYPE_GET_LIST:
    ROLE_MISSION_TYPE_POST:
    ROLE_MISSION_TYPE_PUT:
    ROLE_MISSION_TYPE_PATCH:
    ROLE_MISSION_TYPE_DELETE:
    ROLE_MISSION_TYPE_GET_ITEM:

    # NEGATIVE_POINT RELATED ROLES
    ROLE_NEGATIVE_POINT_GET_LIST:
    ROLE_NEGATIVE_POINT_POST:
    ROLE_NEGATIVE_POINT_PUT:
    ROLE_NEGATIVE_POINT_PATCH:
    ROLE_NEGATIVE_POINT_DELETE:
    ROLE_NEGATIVE_POINT_GET_ITEM:

    # POSITIVE_POINT RELATED ROLES
    ROLE_POSITIVE_POINT_GET_LIST:
    ROLE_POSITIVE_POINT_POST:
    ROLE_POSITIVE_POINT_PUT:
    ROLE_POSITIVE_POINT_PATCH:
    ROLE_POSITIVE_POINT_DELETE:
    ROLE_POSITIVE_POINT_GET_ITEM:

    # STEP RELATED ROLES
    ROLE_STEP_GET_LIST:
    ROLE_STEP_POST:
    ROLE_STEP_PUT:
    ROLE_STEP_PATCH:
    ROLE_STEP_DELETE:
    ROLE_STEP_GET_ITEM:

    # USER RELATED ROLES
    ROLE_USER_GET_LIST:
    ROLE_USER_POST:
    ROLE_USER_PUT:
    ROLE_USER_PATCH:
    ROLE_USER_DELETE:
    ROLE_USER_GET_ITEM:

    # VULN RELATED ROLES
    ROLE_VULN_GET_LIST:
    ROLE_VULN_POST:
    ROLE_VULN_PUT:
    ROLE_VULN_PATCH:
    ROLE_VULN_DELETE:
    ROLE_VULN_GET_ITEM:

    # VULN_TYPE RELATED ROLES
    ROLE_VULN_TYPE_GET_LIST:
    ROLE_VULN_TYPE_POST:
    ROLE_VULN_TYPE_PUT:
    ROLE_VULN_TYPE_PATCH:
    ROLE_VULN_TYPE_DELETE:
    ROLE_VULN_TYPE_GET_ITEM:
      - ROLE_USER


    ROLE_CLIENT_MANAGE:
      - ROLE_CLIENT_GET_LIST
      - ROLE_CLIENT_POST
      - ROLE_CLIENT_PUT
      - ROLE_CLIENT_PATCH
      - ROLE_CLIENT_DELETE
      - ROLE_CLIENT_GET_ITEM

    ROLE_HOST_MANAGE:
      - ROLE_HOST_GET_LIST
      - ROLE_HOST_POST
      - ROLE_HOST_PUT
      - ROLE_HOST_PATCH
      - ROLE_HOST_DELETE
      - ROLE_HOST_GET_ITEM
      - ROLE_HOST_UPLOAD

    ROLE_HOST_VULN_MANAGE:
      - ROLE_HOST_VULN_GET_LIST
      - ROLE_HOST_VULN_POST
      - ROLE_HOST_VULN_PUT
      - ROLE_HOST_VULN_PATCH
      - ROLE_HOST_VULN_DELETE
      - ROLE_HOST_VULN_GET_ITEM

    ROLE_IMPACT_MANAGE:
      - ROLE_IMPACT_GET_LIST
      - ROLE_IMPACT_POST
      - ROLE_IMPACT_PUT
      - ROLE_IMPACT_PATCH
      - ROLE_IMPACT_DELETE
      - ROLE_IMPACT_GET_ITEM

    ROLE_MISSION_MANAGE:
      - ROLE_MISSION_GET_LIST
      - ROLE_MISSION_POST
      - ROLE_MISSION_PUT
      - ROLE_MISSION_PATCH
      - ROLE_MISSION_DELETE
      - ROLE_MISSION_GET_ITEM

    ROLE_MISSION_TYPE_MANAGE:
      - ROLE_MISSION_TYPE_GET_LIST
      - ROLE_MISSION_TYPE_POST
      - ROLE_MISSION_TYPE_PUT
      - ROLE_MISSION_TYPE_PATCH
      - ROLE_MISSION_TYPE_DELETE
      - ROLE_MISSION_TYPE_GET_ITEM

    ROLE_NEGATIVE_POINT_MANAGE:
      - ROLE_NEGATIVE_POINT_GET_LIST
      - ROLE_NEGATIVE_POINT_POST
      - ROLE_NEGATIVE_POINT_PUT
      - ROLE_NEGATIVE_POINT_PATCH
      - ROLE_NEGATIVE_POINT_DELETE
      - ROLE_NEGATIVE_POINT_GET_ITEM

    ROLE_POSITIVE_POINT_MANAGE:
      - ROLE_POSITIVE_POINT_GET_LIST
      - ROLE_POSITIVE_POINT_POST
      - ROLE_POSITIVE_POINT_PUT
      - ROLE_POSITIVE_POINT_PATCH
      - ROLE_POSITIVE_POINT_DELETE
      - ROLE_POSITIVE_POINT_GET_ITEM

    ROLE_STEP_MANAGE:
      - ROLE_STEP_GET_LIST
      - ROLE_STEP_POST
      - ROLE_STEP_PUT
      - ROLE_STEP_PATCH
      - ROLE_STEP_DELETE
      - ROLE_STEP_GET_ITEM

    ROLE_USER_MANAGE:
      - ROLE_USER_GET_LIST
      - ROLE_USER_POST
      - ROLE_USER_PUT
      - ROLE_USER_PATCH
      - ROLE_USER_DELETE
      - ROLE_USER_GET_ITEM

    ROLE_VULN_MANAGE:
      - ROLE_VULN_GET_LIST
      - ROLE_VULN_POST
      - ROLE_VULN_PUT
      - ROLE_VULN_PATCH
      - ROLE_VULN_DELETE
      - ROLE_VULN_GET_ITEM

    ROLE_VULN_TYPE_MANAGE:
      - ROLE_VULN_TYPE_GET_LIST
      - ROLE_VULN_TYPE_POST
      - ROLE_VULN_TYPE_PUT
      - ROLE_VULN_TYPE_PATCH
      - ROLE_VULN_TYPE_DELETE
      - ROLE_VULN_TYPE_GET_ITEM


    # BUSINESS ROLES
    ROLE_CLIENT:
      - ROLE_MISSION_GET_ITEM

    ROLE_MANAGER:
      - ROLE_CLIENT
      - ROLE_CLIENT_MANAGE
      - ROLE_MISSION_MANAGE
      - ROLE_HOST_UPLOAD
      - ROLE_USER_MANAGE

    ROLE_PENTESTER:
      - ROLE_CLIENT
      - ROLE_MISSION_GET_ITEM
      - ROLE_MISSION_GET_LIST
      - ROLE_MISSION_PATCH
      - ROLE_MISSION_PUT
      - ROLE_STEP_MANAGE
      - ROLE_USER_GET_ITEM
      - ROLE_USER_GET_LIST
      - ROLE_USER_PATCH
      - ROLE_USER_PUT
      - ROLE_IMPACT_GET_LIST
      - ROLE_VULN_MANAGE
      - ROLE_VULN_TYPE_MANAGE
      - ROLE_HOST_VULN_MANAGE
      - ROLE_HOST_UPLOAD

    ROLE_ADMIN:
      - ROLE_PENTESTER
      - ROLE_MANAGER
      - ROLE_CLIENT
      - ROLE_CLIENT_MANAGE
      - ROLE_HOST_MANAGE
      - ROLE_IMPACT_MANAGE
      - ROLE_MISSION_MANAGE
      - ROLE_MISSION_TYPE_MANAGE
      - ROLE_NEGATIVE_POINT_MANAGE
      - ROLE_POSITIVE_POINT_MANAGE
      - ROLE_VULN_MANAGE
      - ROLE_VULN_TYPE_MANAGE

  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    #il ajwt:
      #lexik_jwt: ~
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/_(profiler|wdt)
      security: false
    api:
      pattern: ^/api
      stateless: true
      anonymous: true
      provider: app_user_provider
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
    login:
      pattern:  ^/authentication_token
      stateless: true
      anonymous: true
      json_login:
        check_path: /authentication_token
        username_path: username
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    main:
      anonymous: true

  access_control:
    - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Allows accessing the Swagger UI
    - { path: ^/authentication_token, roles: IS_AUTHENTICATED_ANONYMOUSLY } # IS_AUTHENTICATED_FULLY
    - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
